#!/bin/bash
# runner 1.0.4
# Runner script to run scripts hosted remotely

set -euo pipefail
Gre='\e[1;32m' Red='\e[1;31m' Pur='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

Utility="$(basename $0)" # This script filename

#BaseSite="https://raw.githubusercontent.com/git719/tips/refs/heads/main"
BaseSite="https://que.one"
Remote="${BaseSite}/scripts/${Utility}"

# Create a temporary directory
TempDir=$(mktemp -d)
ExitFunc() {
    rm -rf "$TempDir"
}
trap ExitFunc EXIT

# Fetch the script into the temp directory
TempFile="$TempDir/$Utility"
curl -s "$Remote" -o "$TempFile"
chmod +x "$TempFile"

# Execute the fetched script with only the user-provided arguments
"$TempFile" "$@"
